export * from "./usuario.service"
export * from "./administrador.service"
export * from "./residente.service"
export * from "./nota.service"
export * from "./sede.service"
export * from "./especialidad.service"
export * from "./docente.service"
