export * from "./useResidentes"
export * from "./useNotas"
export * from "./useAdministradores"
export * from "./useUsuarios"
export * from "./useSedes"
export * from "./useEspecialidades"
export * from "./useDocentes"
